services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=memo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  memo-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/memo
      - JWT_SECRET=your-secret-key-here
      - RUST_LOG=debug
    volumes:
      - ./db:/app/db
      - ./db/migrations:/app/db/migrations
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
